### ISSUE TITLE
Setting values to a column that do not match the scheme type

### ISSUE THREAD

**Issue by frankenjoe** [audeering/audformat#138]
There is currently no check if the values set to a column match the scheme type.

E.g. setting float values to a string column works (most likely because the dtype of a string column is `object`):

```python
import audformat

db = audformat.Database('test')
db['table'] = audformat.Table(audformat.filewise_index(['f1', 'f2']))

# setting float values to a string column
db.schemes['string'] = audformat.Scheme(audformat.define.DataType.STRING)
db['table']['string'] = audformat.Column(scheme_id='string')
db['table']['string'].set(['a', 1.0])
db['table']['string'].get()
```
```
file
f1    a
f2    1
Name: string, dtype: object
```

Setting strings to a float column, on the other hand, fails:

```python
db.schemes['float'] = audformat.Scheme(audformat.define.DataType.FLOAT)
db['table']['float'] = audformat.Column(scheme_id='float')
db['table']['float'].set(['a', 1.0])
```
```
ValueError: could not convert string to float: 'a'
```

**Comment by hagenw** [comment]
I think this issue might also get solved by https://github.com/audeering/audformat/pull/212. 

Your first example would also not fail, but it would convert everything to a string and return:

```
file
f1      a
f2    1.0
Name: string, dtype: string
```

The same happens if you specify explicetly the dtype of the input data by handing in a series;
```python
y = pd.Series([1, 1.0], dtype=float)
db['table']['string'].set(y)
db['table']['string'].get()
```
would then return
```
file
f1    1.0
f2    1.0
Name: string, dtype: string
```
I think the behavior is ok, as the dtype should be specified with the help of the scheme and one could expect that everything gets converted accordingly.

The alternative would mean we need to check the given input type, which is easy for a series, but could be costly for a list containing millions of entries.

**Comment by frankenjoe** [comment]
I would also say the behavior is ok, we could even call it a feature :)

**Comment by hagenw** [comment]
But maybe we have to update the docstring of `audformat.Column.set()` then as it reads:

![image](https://user-images.githubusercontent.com/173624/180373602-31d73ed9-358b-4e3f-aa62-934f54a77599.png)

which is not true for input that can be converted to the dtype of the scheme as shown above.

**Comment by frankenjoe** [comment]
Maybe we can write: "If a column is assigned to a Scheme values will be automatically converted to match its dtype. If this is not possible an error is raised."
