### ISSUE TITLE
Make sure misc tables are updated in the correct order in Database.update()

### ISSUE THREAD

**Issue by hagenw** [audeering/audformat#258]
As stated at https://github.com/audeering/audformat/pull/255#discussion_r934199932 and https://github.com/audeering/audformat/pull/255#issuecomment-1199435645 we need to figure out the order in which misc tables are updated as they can define schemes used in other misc tables, and those tables should be loaded first before the scheme is used.

It might even be that we have to forbid circular definitions, or at least check if it can be loaded. E.g. if table A uses a scheme from table B and vice versa.

**Comment by frankenjoe** [comment]
Usually, the fact hat we iterate the `MiscTable` objects in the order they were added ensures that a `MiscTable` used as scheme in another `MiscTable` is updated first, because the scheme has to exist when it is linked by the table. However, there might be one exception and that is if the user updates a scheme from a list / dict of labels to a `MiscTable`. I'm not sure if this is currently possible or if we want to support it. But if we do, then we need some kind of dependency resolving. As far as I see this is also the only possible way to create a circular dependency.

**Comment by frankenjoe** [comment]
> However, there might be one exception and that is if the user updates a scheme from a list / dict of labels to a `MiscTable`.

With the fix provided in #263 it is indeed possible to replace a list with a table in a scheme:

```python
db = audformat.testing.create_db(minimal=True)
db.schemes['labels'] = audformat.Scheme(labels=['a', 'b'])

db['misc'] = audformat.MiscTable(pd.Index([1, 2], name='idx'))
db['misc']['column'] = audformat.Column(scheme_id='labels')
db['misc']['column'].set(['a', 'b'])

db['labels'] = audformat.MiscTable(pd.Index(['b', 'c'], dtype='string', name='idx'))
db.schemes['labels'].replace_labels('labels')

db['misc'].get()
```
```
    column
idx       
1      NaN
2        b
```

If we now iterate the misc tables, the scheme table comes after the table that references the scheme:

```python
for table in db.misc_tables:
  print(table)
```
```
misc
labels
```

**Comment by frankenjoe** [comment]
I'm not sure yet about the consequences, though :)

**Comment by frankenjoe** [comment]
One way to avoid circular definitions would be that we forbid that a `MiscTable` that is used as scheme can have columns that are again linked to another  `MiscTable`.

**Comment by hagenw** [comment]
The same we have to forbid. For the other I'm not completely sure. Will try to find an example where it might be useful.
If I cannot find one, I guess we can simply forbid it.

**Comment by frankenjoe** [comment]
> The same we have to forbid. For the other I'm not completely sure. Will try to find an example where it might be useful.
> If I cannot find one, I guess we can simply forbid it.

I guess there could be a use-case, but it will make the order we have to update tables quite complicated. If we do not allow it, we can do in the following order:

1. `MiscTable` objects that are used by a scheme
2. Remaining `MIscTable` objects
3. `Table` objects

**Comment by hagenw** [comment]
It might be useful to support nested misc tables as scheme for very complicated schemes, e.g.

```python
db['location'] = audformat.MiscTable(pd.Index(['loc1', 'loc2'], dtype='string', name='location'))
db['location']['coordinates'] = ...
db['location']['height'] = ...
db['location']['indoor'] = ...
...
db.schemes['location'] = audformat.Scheme('str', labels='location')
db['speaker'] = audformat.MiscTable(pd.Index(['spk1'], dtype='string', name='speaker'))
db['speaker']['location'] = audformat.Column(scheme_id='location')
...
db.schemes['speaker'] = audformat.Scheme('str', labels='speaker')
```

The problem is of cause, that we also do not support this with `map=`, so most likely we should forbid it.

**Comment by frankenjoe** [comment]
> The problem is of cause, that we also do not support this with map=, so most likely we should forbid it.

Yes, that's another argument to forbid it.

So I suggest we forbid it for the moment, we can still add it later if we see the need for it.

**Comment by frankenjoe** [comment]
We now have #274 to forbid that a misc table used in a scheme can have columns that link another misc table. One argument was that this will make it easier to define the order in which we update misc tables in `Database.update()`. Our concern was that we first have to update misc tables linked by other tables. However, I just realized that as soon as we use a misc table in a scheme we actually cannot update the index of that table because this would change the labels of the scheme, which is something we do not support:

```python
db1 = audformat.testing.create_db(minimal=True)
db1['misc'] = audformat.MiscTable(pd.Index([0, 1], name='idx'))
db1.schemes['scheme'] = audformat.Scheme(dtype='int', labels='misc')
db1['table'] = audformat.Table(audformat.filewise_index(['f1', 'f2']))
db1['table']['column'] = audformat.Column(scheme_id='scheme')
db1['table']['column'].set([0, 1])

db2 = audformat.testing.create_db(minimal=True)
db2['misc'] = audformat.MiscTable(pd.Index([1, 2], name='idx'))
db2.schemes['scheme'] = audformat.Scheme(dtype='int', labels='misc')
db2['table'] = audformat.Table(audformat.filewise_index(['f1', 'f2']))
db2['table']['column'] = audformat.Column(scheme_id='scheme')
db2['table']['column'].set([1, 2])

db1.update(db2)
```
```
CategoricalDtype(categories=[0, 1], ordered=False) != CategoricalDtype(categories=[1, 2], ordered=False).
```

This means that the order in which we update (misc) tables actually does not matter!

There seems to be only one special case we have to consider and that is we update a misc table that is used by db1 in a scheme, but not by db2:

```python
db1 = audformat.testing.create_db(minimal=True)
db1['misc'] = audformat.MiscTable(pd.Index([0, 1], name='idx'))
db1.schemes['scheme'] = audformat.Scheme(dtype='int', labels='misc')
db1['table'] = audformat.Table(audformat.filewise_index(['f1', 'f2']))
db1['table']['column'] = audformat.Column(scheme_id='scheme')
db1['table']['column'].set([0, 1])

db2 = audformat.testing.create_db(minimal=True)
db2['misc'] = audformat.MiscTable(pd.Index([1, 2], name='idx'))

db1.update(db2)
```

We can see that this correctly updates the misc table:

```python
db1['misc'].get()
```
```
Columns: []
Index: [0, 1, 2]
```

But it does not update the table of db1 that links to the scheme:

```python
db1['table']['column'].get().dtype.categories
```
```
Int64Index([0, 1], dtype='int64')
```

So as long as we do not allow that a misc table used in a scheme by both databases is updated, we probably don't need #274. Instead we should call `replace_labels()` on all schemes that use a misc table and is updated.

**Comment by hagenw** [comment]
In general, updating schemes when updating a database was also requested at https://github.com/audeering/audformat/issues/61 as a feature to have. So it might be interesting to introduce it.

In https://github.com/audeering/audformat/issues/61 I also stated that `audformat.utils.join_schemes()` is a possible solution. How does this work with misc tables at the moment?

**Comment by frankenjoe** [comment]
> In #61 I also stated that `audformat.utils.join_schemes()` is a possible solution. How does this work with misc tables at the moment?

Seems we have to update `audformat.utils.join_schemes()` first to support misc tables:

```python
...
audformat.utils.join_schemes([db1, db1], 'scheme')
db1.update(db2)
```
```
ValueError: Supported label types are 'list' and 'dict', but your is '<class 'str'>'
```

**Comment by frankenjoe** [comment]
I created https://github.com/audeering/audformat/pull/275
